### ISSUE TITLE
How to properly render a template inside an google.maps.InfoWindow

### ISSUE THREAD

**Issue by williamledoux** [dburles/meteor-google-maps#50]
Do you know how it could be possible to properly render a template inside an InfoWindow?
I can not use `Blaze.toHTMLWithData` to set the content of the InfoWindow, first because I want the events to trigger and also the InfoWindow content to be reactive.

**Comment by clarkritchie** [comment]
I think that's a limitation of Blaze since `toHTMLWithData` does not provide a reactive data context.   Maybe you can do it with data in the Session var?

Anyhow, I am doing this manually -- recreating the infoWindow manually from a template when the document changes, basically in my observer:

```
changed: function(newDocument, oldDocument) {
                /**
                * Event listener:  Update info window since the document has changed
                */
                var siteInfoWindowContent = Blaze.toHTMLWithData(Template.siteInfoWindow, infoWindowData);
                google.maps.event.addListener(_markers[newDocument._id], 'mouseover', function(event) {
                    infoWindow.setContent(siteInfoWindowContent);
                    infoWindow.open(map.instance, this);
                });
            },
```

You may need to `google.maps.event.clearInstanceListeners(...)` before you call `addListener` on the placemark again.
