### ISSUE TITLE
Content Security Policy violation

### ISSUE THREAD

**Issue by josephdburdick** [dburles/meteor-google-maps#88]
Hi @dburles,
I've started using [Base](https://themeteorchef.com/base/) as a boilerplate for my Meteor development and I've run into the following issue while trying to add a Google map with the default options you've provided:

```
Refused to load the script 'https://maps.googleapis.com/maps/api/js?v=3.exp&callback=GoogleMaps.initialize' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline’".
```

My Google searching hasn't returned anything substantial so I thought I'd ask.

**Comment by dburles** [comment]
Hey @josephdburdick that boilerplate uses the `browser-policy` package. You'll need to configure some rules. Put these somewhere on the client:

``` js
    BrowserPolicy.content.allowOriginForAll('*.googleapis.com');
    BrowserPolicy.content.allowOriginForAll('*.gstatic.com');
    BrowserPolicy.content.allowEval('https://ajax.googleapis.com');  
```

**Comment by josephdburdick** [comment]
@dburles thanks for the tip! I also notice now that this is related to #33. I'll close this for now and reopen if necessary.

**Comment by surbhibh** [comment]
### Getting below error in all the environment. Please help me with this. I tried all the suggested ways.

Refused to create a worker from 'blob:http://localhost:4000/35ba9398-2c4f-429d-b755-6afbc0b94dda' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://*.google-analytics.com https://*.gstatic.com 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.
